import './global.scss'
import { Montserrat } from 'next/font/google'
import { UserIdProvider } from '@/app/UserIdProvider'

const montserrat = Montserrat({
  weight: ['600', '400'],
  subsets: ['cyrillic', 'latin']
})
export const metadata = {
  title: 'Tinkoff Cup',
  // todo: добавить иконку
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='ru'>
      <UserIdProvider>
        <body className={montserrat.className}>{children}</body>
      </UserIdProvider>
    </html>
  )
}
