name: Check
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Clean install
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn run test
      - name: Build
        run: yarn run build
